# Preliminary Analysis
Large-scale analysis about telescope size, request type, etc

## Setup

In [1]:
import pandas as pd
import pickle
import json
import os
import datetime as dt
from matplotlib import pyplot as plt

In [71]:
root = "D:/_DATA_ANALYSIS_FILES"
print(os.path.isdir(root))

True

## Load Data

### RequestGroups

In [5]:
df_list_group = []
for filename in os.listdir(root):
    if "_requestgroup." in filename:
        filepath = os.path.join(root, filename)
        data = pickle.load(open(filepath, "rb"))
        data = data[data["id"].isin(requestgroup_ids)]
        df_list_group.append(data)
df_group = pd.concat(df_list_group)
del df_list_group

df_group

,id,name,observation_type,operator,ipp_value,created,state,modified,proposal_id,submitter_id
0,1381010,Daily,DIRECT,SINGLE,1.00,2022-01-23T19:44:08.478Z,PENDING,2022-01-23T19:44:08.478Z,ASAS,1218
1,1083530,LCOGT,DIRECT,SINGLE,1.00,2020-11-07T00:05:11.029Z,WINDOW_EXPIRED,2020-11-07T07:25:02.229Z,calibrate,2791
2,947053,auto_focus check,NORMAL,SINGLE,1.05,2020-02-25T22:00:09.547Z,WINDOW_EXPIRED,2020-02-26T06:20:04.211Z,auto_focus,2791
3,1001499,auto_focus,DIRECT,SINGLE,1.00,2020-06-13T01:05:27.168Z,WINDOW_EXPIRED,2020-06-13T08:05:02.374Z,auto_focus,2791
4,1001493,auto_focus,DIRECT,SINGLE,1.00,2020-06-13T01:05:22.743Z,WINDOW_EXPIRED,2020-06-13T08:05:02.486Z,auto_focus,2791
...,...,...,...,...,...,...,...,...,...,...
691928,1232876,2019hhc,NORMAL,SINGLE,1.02,2021-06-10T00:54:08.936Z,WINDOW_EXPIRED,2021-06-12T00:55:11.320Z,CON2021A-012,2240
691929,1232875,2019dwy,NORMAL,SINGLE,1.02,2021-06-10T00:54:06.016Z,WINDOW_EXPIRED,2021-06-12T00:55:11.408Z,CON2021A-012,2240
691930,1232874,2019dwy,NORMAL,SINGLE,1.02,2021-06-10T00:54:03.318Z,WINDOW_EXPIRED,2021-06-12T00:55:11.512Z,CON2021A-012,2240
691931,1232873,2019dwy,NORMAL,SINGLE,1.02,2021-06-10T00:54:01.010Z,WINDOW_EXPIRED,2021-06-12T00:55:11.596Z,CON2021A-012,2240
691932,1232931,2020bio,NORMAL,SINGLE,1.02,2021-06-10T00:56:35.440Z,WINDOW_EXPIRED,2021-06-12T01:00:34.505Z,CON2021A-012,2240

### Requests

In [6]:
df_list_request = []
for filename in os.listdir(root):
    if "_request." in filename:
        filepath = os.path.join(root, filename)
        data = pickle.load(open(filepath, "rb"))
        df_list_request.append(data)
df_request = pd.concat(df_list_request)
del df_list_request
# df_request = df_request[["id", "state", "modified", "acceptability_threshold", "configuration_repeats", "request_group_id"]]

requestgroup_ids = df_request["request_group_id"].unique().tolist()
df_request

,id,observation_note,state,modified,created,acceptability_threshold,request_group_id,extra_params,configuration_repeats,optimization_type
0,3053362,,WINDOW_EXPIRED,2023-01-08T11:50:03.905Z,2022-11-16T09:56:21.069Z,90.0,1581143,{},1,TIME
1,3097579,,COMPLETED,2023-01-28T02:54:33.079Z,2023-01-09T00:00:29.738Z,90.0,1615811,{},1,TIME
2,3057472,,COMPLETED,2023-01-29T01:25:32.553Z,2022-11-18T12:27:48.096Z,90.0,1582590,{},1,TIME
3,3112564,,COMPLETED,2023-01-29T01:32:09.843Z,2023-01-28T10:56:14.706Z,90.0,1628904,{},1,TIME
4,3112973,,COMPLETED,2023-01-29T01:35:53.039Z,2023-01-28T20:30:07.769Z,90.0,1629274,{},1,TIME
...,...,...,...,...,...,...,...,...,...,...
1062601,2327326,,WINDOW_EXPIRED,2021-01-20T18:35:11.282Z,2020-12-13T10:46:42.515Z,90.0,1107823,{},1,TIME
1062602,2327327,,WINDOW_EXPIRED,2021-01-21T00:35:10.687Z,2020-12-13T10:46:42.532Z,90.0,1107823,{},1,TIME
1062603,2327328,,COMPLETED,2021-01-21T05:02:14.148Z,2020-12-13T10:46:42.552Z,90.0,1107823,{},1,TIME
1062604,2327329,,COMPLETED,2021-01-21T11:32:27.938Z,2020-12-13T10:46:42.575Z,90.0,1107823,{},1,TIME
1062605,2327330,,COMPLETED,2021-01-21T15:09:31.023Z,2020-12-13T10:46:42.594Z,90.0,1107823,{},1,TIME

### Locations

df_list_location = []
for filename in os.listdir(root):
    if "_location." in filename:
        filepath = os.path.join(root, filename)
        data = pickle.load(open(filepath, "rb"))
        df_list_location.append(data)
df_location = pd.concat(df_list_location)
del df_list_location

df_location

### Proposals

In [60]:
df_proposal = pickle.load(open(os.path.join(root, "proposals_proposal.pkl"), "rb"))
df_proposal

,id,active,title,abstract,tac_priority,tac_rank,public,non_science,direct_submission,sca_id,tags
0,LCOELP-002,False,Active W UMa stars,,50,0,False,False,False,LCOGT,{}
1,CON2018A-006,False,AGN Reverberation Lags,,25,6,False,False,False,LCOGT,{}
2,DDTELP-003,False,Astrophotography,,50,0,False,False,False,LCOGT,{}
3,DDT2020A-004,False,Catch a Fading Star 2: High-Cadence Photometry...,,20,4,False,False,False,LCO,{}
4,TAU2019B-007,False,changing-look AGNs,,20,7,False,False,False,TAU,{}
...,...,...,...,...,...,...,...,...,...,...,...
2607,SOAR2023B-020,False,Very Rapid-Response Spectroscopy of Supernovae...,,20,20,False,False,False,SOAR,{}
2608,FTPEPO2021A-001,True,"Consolidated Activities Regarding Moon, Earth ...",,13,1,True,False,False,FTP,{public}
2609,KEY2023B-005,True,LCO follow up of TESS transiting planet candid...,,30,5,False,False,False,SCICOLLAB,{}
2610,SOAR2023B-005,False,Testing planetary formation paradigms via SOAR...,,20,5,False,False,False,SOAR,{}
2611,NSF2023B-014,True,White Dwarf Companions to Sub-Subgiants and Re...,,30,14,False,False,False,NSF,{}

In [61]:
df_proposal[df_proposal["non_science"]]

,id,active,title,abstract,tac_priority,tac_rank,public,non_science,direct_submission,sca_id,tags
46,Cal-TOM scheduler,False,Testing Calibration-TOM requests submitted to ...,,10,1,False,True,False,LCO,{}
66,OGG_calib,False,Calibrations for the OGG site,,1000,0,False,True,False,LCOGT,{}
90,SSA-ADS-cal,False,Calibration observations for ADS,,100,1,False,True,False,LCOGT,{}
107,ENG2017AB-004,False,0m4 Testing,,10,1,False,True,False,LCOGT,{}
130,CON2023B-011,True,Cardiff University Physics Lab,,25,11,True,True,False,LCO,{}
138,standard,False,LCOGT Photometric Standards,,10,0,False,True,True,DIRECT,{}
332,ENG2017AB-003,False,Sinistro testing,,100,1,False,True,False,LCOGT,{}
362,LCOSchedulerTest,True,Test Requests for the Scheduling Project,,1000,0,False,True,True,LCOGT,{internal}
379,auto_focus,True,LCOGT Autofocus,,10,0,True,True,True,DIRECT,{public}
450,ENG2017AB-002,False,FLOYDS Engineering,,1000,0,False,True,False,LCOGT,{}
581,SSA-AGI-cal,False,Calibration observations for AGI,,1000,1,False,True,False,LCOGT,{}
591,SSA-AGI-obs,False,Satellite observations for AGI,,1000,1,False,True,False,LCOGT,{}
603,LCOEngineering,True,LCOEngineering,,1000,0,False,True,True,DIRECT,{internal}
634,SSA-ADS-obs,False,Satellite observations for ADS,,100,1,False,True,False,LCOGT,{}
835,SSA-FOI-obs,False,Satellite observations for FOI,,1000,1,False,True,False,LCOGT,{}
877,urgent_auto_focus,True,urgent_auto_focus,,60,0,True,True,True,DIRECT,{public}
909,ENG2017AB-001,False,NRES Commissioning,,20,1,False,True,True,LCOGT,{}
997,SSA-LPL-obs,False,Satellite observations for U. Liverpool,,1000,1,False,True,False,LCOGT,{}
1662,COJ_calib,False,Calibrations for the COJ site,,1000,0,False,True,False,LCOGT,{}
2174,SSA-FOI-cal,False,Calibration observations for FOI,,1000,1,False,True,False,LCOGT,{}
2177,pointing,True,Proposal for pointing/zeroset calibrations,,10,0,True,True,False,LCOGT,{public}
2196,FLOYDS standards,True,FLOYDS standards,,100,0,True,True,False,LCOGT,{public}
2198,NRES standards,True,NRES standards,,1000,0,True,True,True,LCOGT,{public}
2513,rescue_auto_focus,True,rescue_auto_focus,,999,0,True,True,True,DIRECT,{public}
2516,Photometric standards,True,Photometric standards,,10,0,True,True,True,LCOGT,{public}

In [70]:
df_proposal[~df_proposal["non_science"] & (~df_proposal["id"].str.contains("-"))]

,id,active,title,abstract,tac_priority,tac_rank,public,non_science,direct_submission,sca_id,tags
6,Eng,False,Engineering (deprecated),,50,0,False,False,False,LCOGT,{}
89,TOM demo scheduler,False,TOM demo scheduler,,10,1,False,False,False,LCO,{}
91,DeltaRho Science,True,DeltaRho Science Validation,,20,1,False,False,False,LCOGT,{}
97,MuSCAT Commissioning,True,MuSCAT Commissioning,,40,0,True,False,False,LCO,{}
164,calibrate,True,LCOGT calibrations,,10000,0,True,False,True,DIRECT,{public}
207,LSC_calib,False,Calibrations for the LSC site,,10,0,False,False,False,LCOGT,{}
208,dove2,False,Dove 2 satellite tracking,,90,0,False,False,False,LCOGT,{}
277,DeltaRho Commissioning,True,DeltaRho Commissioning,,1000,1,False,False,True,LCOGT,{}
572,LCOEPO4,False,Hawaii EPO non-proprietary,,50,0,True,False,False,LCOEPO,{}
638,Spectral_Standard,False,Spectral standards for FLOYDS,,10,0,True,False,False,LCOGT,{}
727,ASAS,True,ASAS SN proposal,,20,1,False,False,True,ASAS,{}
750,LCOEPO2,False,LCOGT Education,,50,0,True,False,False,LCOEPO,{}
813,CPT_calib,False,Calibrations for the CPT site,,10,0,False,False,False,LCOGT,{}
1028,LCOEPO1,False,Proprietary education development projects,,50,0,True,False,False,LCOGT,{}
1055,Scheduler Testing,False,Scheduler Testing (deprecated),,50,0,False,False,False,LCOGT,{}
1065,LCOEPO3,False,Hawaii EPO proprietary proposal,,50,0,False,False,False,LCOGT,{}
1649,BPL_calib,False,Calibrations for the BPL site,,10,0,False,False,False,LCOGT,{}
1663,ELP_calib,False,Calibrations for the ELP site,,10,0,False,False,False,LCOGT,{}
1674,SQA_calib,False,Calibrations for the SQA site,,90,0,False,False,False,LCOGT,{}

# Analysis

## Do DIRECT Requests have Locations?
No.

In [11]:
direct_group_ids = df_group[df_group["observation_type"]=="DIRECT"]["id"].unique().tolist()
direct_request_ids = df_request[df_request["request_group_id"].isin(direct_group_ids)]["id"].unique().tolist()
direct_locations = df_location[df_location["request_id"].isin(direct_request_ids)]
direct_locations

Empty DataFrame
Columns: [id, telescope_class, site, enclosure, telescope, request_id]
Index: []

## Observation Type Split
Looking at number of both RequestGroups and Requests.

In [37]:
obstype_group_count = df_group["observation_type"].value_counts()
obstype_group_perc = obstype_group_count/len(df_group)*100
temp = df_request.merge(df_group[["id", "observation_type"]], left_on="request_group_id", right_on="id")
obstype_req_count = temp["observation_type"].value_counts()
obstype_req_perc = obstype_req_count/len(df_request)*100
pd.concat([obstype_group_count, obstype_group_perc, obstype_req_count, obstype_req_perc], axis=1)\
    .set_axis(["RequestGroup Count", "RequestGroup %", "Request Count", "Request %"], axis=1)

                  RequestGroup Count  RequestGroup %  Request Count  Request %
observation_type
NORMAL                        399241       57.699373         762310  71.739666
DIRECT                        281636       40.702785         281636  26.504273
TIME_CRITICAL                  10394        1.502169          17997   1.693666
RAPID_RESPONSE                   662        0.095674            663   0.062394

## Telescope Class Split
Obviously, don't include DIRECT requests, as they do not have Location data.

In [41]:
temp

,id_x,observation_note,state,modified,created,acceptability_threshold,request_group_id,extra_params,configuration_repeats,optimization_type,id_y,observation_type
0,3053362,,WINDOW_EXPIRED,2023-01-08T11:50:03.905Z,2022-11-16T09:56:21.069Z,90.0,1581143,{},1,TIME,1581143,NORMAL
1,3053389,,WINDOW_EXPIRED,2023-01-17T11:50:04.051Z,2022-11-16T09:56:21.686Z,90.0,1581143,{},1,TIME,1581143,NORMAL
2,3053422,,WINDOW_EXPIRED,2023-01-28T11:50:05.092Z,2022-11-16T09:56:22.238Z,90.0,1581143,{},1,TIME,1581143,NORMAL
3,3053377,,WINDOW_EXPIRED,2023-01-13T11:50:06.245Z,2022-11-16T09:56:21.407Z,90.0,1581143,{},1,TIME,1581143,NORMAL
4,3053218,,COMPLETED,2022-11-16T10:27:49.494Z,2022-11-16T09:56:18.646Z,90.0,1581143,{},1,TIME,1581143,NORMAL
...,...,...,...,...,...,...,...,...,...,...,...,...
1062601,2327171,,WINDOW_EXPIRED,2020-12-14T02:45:07.843Z,2020-12-13T10:40:37.960Z,90.0,1107821,{},1,TIME,1107821,NORMAL
1062602,2327168,,WINDOW_EXPIRED,2020-12-14T10:25:07.398Z,2020-12-13T10:20:08.025Z,90.0,1107818,{},1,TIME,1107818,NORMAL
1062603,2359397,,COMPLETED,2021-01-18T09:16:10.853Z,2021-01-17T17:40:52.817Z,90.0,1131247,{},1,TIME,1131247,NORMAL
1062604,2359738,Submitted to scheduler.,WINDOW_EXPIRED,2021-01-18T18:15:03.922Z,2021-01-18T02:00:40.082Z,90.0,1131558,{},1,TIME,1131558,NORMAL
1062605,2359730,Submitted to scheduler.,WINDOW_EXPIRED,2021-01-18T18:15:04.013Z,2021-01-18T02:00:34.655Z,90.0,1131550,{},1,TIME,1131550,NORMAL

In [47]:
temp2 = temp.merge(df_location, left_on="id_x", right_on="request_id")
location_counts = temp2[["observation_type", "telescope_class"]].value_counts()
location_perc = location_counts/len(df_location)*100
pd.concat([location_counts, location_perc], axis=1).set_axis(["Count", "%"], axis=1)

                                   Count          %
observation_type telescope_class
NORMAL           1m0              441583  56.542889
                 0m4              245319  31.412090
                 2m0               73124   9.363228
TIME_CRITICAL    1m0               11841   1.516191
                 0m4                4762   0.609755
NORMAL           4m0                2284   0.292457
TIME_CRITICAL    2m0                1394   0.178496
RAPID_RESPONSE   1m0                 575   0.073626
                 2m0                  85   0.010884
                 0m4                   3   0.000384

In [58]:
for observation_type, group in temp2.groupby("observation_type"):
    if observation_type == "DIRECT":
        continue
    for telescope_class, group2 in group.groupby("telescope_class"):
        print(observation_type, telescope_class, 
              len(group2), 
              f"{round(len(group2)/len(group)*100, 2)}%", 
              len(group2["request_group_id"].unique()),
              f"{round(len(group2['request_group_id'].unique())/len(group['request_group_id'].unique())*100, 2)}%")
        
    # print(observation_type)
    # print(group["telescope_class"].value_counts())
    # print(group["telescope_class"].value_counts()/len(group)*100)
    # print()

NORMAL 0m4 245319 32.18% 115470 28.92%
NORMAL 1m0 441583 57.93% 229910 57.59%
NORMAL 2m0 73124 9.59% 51608 12.93%
NORMAL 4m0 2284 0.3% 2275 0.57%
RAPID_RESPONSE 0m4 3 0.45% 3 0.45%
RAPID_RESPONSE 1m0 575 86.73% 574 86.71%
RAPID_RESPONSE 2m0 85 12.82% 85 12.84%
TIME_CRITICAL 0m4 4762 26.46% 1626 15.64%
TIME_CRITICAL 1m0 11841 65.79% 7600 73.12%
TIME_CRITICAL 2m0 1394 7.75% 1168 11.24%

In [40]:
non_direct_groups = df_group[df_group["observation_type"]!="DIRECT"]["id"].unique().tolist()
non_direct_requests = df_request[df_request["request_group_id"].isin(non_direct_groups)]["id"].unique().tolist()
non_direct_locations = df_location[df_location["request_id"].isin(non_direct_requests)]
non_direct_locations

             id telescope_class site enclosure telescope  request_id
0       1670008             1m0                              2048275
1       1670009             2m0  coj                         2048300
2       1670010             0m4                              2048301
3       1670011             0m4                              2048302
4       1670012             1m0                              2048303
...         ...             ...  ...       ...       ...         ...
780965  2333520             0m4                              2934440
780966  2333521             0m4                              2934441
780967  2333522             0m4                              2934442
780968  2333523             0m4                              2934443
780969  2333524             0m4                              2934444

[780970 rows x 6 columns]